Repository SWP391-Nhom-4-NET1803/BE_Code_Main, pull requests merged in 2024-07, with the labels that each got.

#47 Minor adjustment
  DentalClinicBookingPlatform/ClinicPlatformDTOs/BookingModels/AppointmentSetting.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/ClinicModels/ClinicInfoModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/ClinicModels/ClinicRegistrationModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/ReportModels/AdminSumarizedInfo.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/BookingRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/ClinicRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/Contracts/IBookingRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/Contracts/IUserRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/UserRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/AdminService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/BookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IAdminService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PaymentService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PlatformClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/UserService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AdminController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AuthController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/BookingController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicServiceController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/CustomerController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/DentistController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ScheduleController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/UserController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Helpers/Models/HttpResponseModel.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Helpers/Models/IHttpResponseModel.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Program.cs
Labels: patch

#49 Added payment functionality
  DentalClinicBookingPlatform/ClinicPlatformBusinessObject/Dentist.cs
  DentalClinicBookingPlatform/ClinicPlatformBusinessObject/Payment.cs
  DentalClinicBookingPlatform/ClinicPlatformBusinessObject/User.cs
  DentalClinicBookingPlatform/ClinicPlatformBusinessObject/UserPanfoymentInfo.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/BookingModels/AppointmentViewModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/PayementModels/PaymentInfoModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/PayementModels/VNPayInfoModel.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/BookingRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/Contracts/IPaymentRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/DentalClinicPlatformContext.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/PaymentRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/BookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IBookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IPaymentService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PaymentService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/BookingController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicServiceController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/DentistController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/PaymentController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Program.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Services/VNPayService/IVNPayService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Services/VNPayService/VNPayService.cs
  database/DatabaseDefinition.sql
Labels: enhancement, patch

#50 Completed Payment Service
  DentalClinicBookingPlatform/ClinicPlatformDTOs/BookingModels/AppointmentRegistrationModel.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/ScheduleRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/BookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IBookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/BookingController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/PaymentController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Program.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Services/EmailService/EmailService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Services/EmailService/IEmailService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Services/VNPayService/VNPayService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/appsettings.json
Labels: documentation, enhancement, patch

#51 Updated booking service
  DentalClinicBookingPlatform/ClinicPlatformServices/BookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/BookingController.cs
Labels: patch

#53 Added reset password with email capability
  DentalClinicBookingPlatform/ClinicPlatformDTOs/MiscModels/PasswordResetModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/TokenModels/TokenInfoModel.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/Contracts/ITokenRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/TokenRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/ITokenService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/TokenService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/UserController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Program.cs
Labels: enhancement

#54 Fixed inconsistent usage of UtcTime
  DentalClinicBookingPlatform/ClinicPlatformDTOs/PayementModels/VNPayInfoModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/ReportModels/AdminSumarizedInfo.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/UserRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/AdminService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/BookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PaymentService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/TokenService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AdminController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AuthController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/BookingController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/PaymentController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/UserController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Program.cs
Labels: patch

#55 Added more return information for booking view
  DentalClinicBookingPlatform/ClinicPlatformDTOs/BookingModels/AppointmentViewModel.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/AuthService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/BookingController.cs
Labels: enhancement

#57 Fixed a bug related to booking
  DentalClinicBookingPlatform/ClinicPlatformServices/BookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IBookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PaymentService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/UserService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/BookingController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/CustomerController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/PaymentController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Helpers/ModelMapper/UserInfoMapper.cs
Labels: enhancement, patch

#56 Add endpoints for admin
  DentalClinicBookingPlatform/ClinicPlatformRepositories/ClinicRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/Contracts/IClinicRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PlatformClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AdminController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/appsettings.json
Labels: enhancement

#58 fix minor problems
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/PaymentController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/appsettings.json
  TestProject/UserRepositoryTesting.cs
Labels: patch

#60 Update multiple endpoints
  DentalClinicBookingPlatform/ClinicPlatformDTOs/PayementModels/PaymentInfoModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/PayementModels/PaymentView.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/CustomerModel/CustomerInfoViewModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/CustomerModel/CustomerUpdateModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/DentistModel/DentistInfoViewModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/DentistModel/DentistUpdateModel.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/UserRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/AuthService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/BookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IUserService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PlatformClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/UserService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AdminController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AuthController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/BookingController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicServiceController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/CustomerController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/DentistController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/PaymentController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Helpers/ModelMapper/UserInfoMapper.cs
Labels: enhancement, patch

#61 Updated for quality assurances
  DentalClinicBookingPlatform/ClinicPlatformDTOs/ClinicModels/ClinicInfoModel.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/AuthService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PlatformClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AdminController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AuthController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Middlewares/Auth/AuthorizationMiddleware.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Program.cs
Labels: enhancement, patch
