Repository SWP391-Nhom-4-NET1803/BE_Code_Main, pull requests merged in 2024-06, with the labels that each got.

#5 Tạo endpoint lấy thông tin người dùng
  Core/Exception/HttpErrorResponse.cs
  Core/Exception/HttpValidResponse.cs
  Core/HttpModels/UserInfoModel.cs
  Core/Misc/GoogleAuthModel.cs
  Repositories/UnitOfWork.cs
  Services/EmailSerivce/EmailService.cs
  Services/TokenManager/IJwtTokenService.cs
  Services/TokenManager/JwtTokenService.cs
  WebAPI/Controllers/AuthenticationController.cs
  WebAPI/Controllers/UsersController.cs
Labels: documentation, enhancement

#13 Added VNPay Intergration
  Core/HttpModels/VNPayInfoModel.cs
  Core/Misc/VNPayCompare.cs
  Services/VNPay/IVNPayService.cs
  Services/VNPay/VNPayService.cs
  WebAPI/Controllers/PaymentController.cs
Labels: enhancement

#17 API đăng kí phòng khám
  Repositories/Models/DentalClinicPlatformContext.cs
  Repositories/Repositories/GenericRepository.cs
  Repositories/UnitOfWork.cs
  WebAPI/Controllers/ClinicsController.cs
  WebAPI/appsettings.json
Labels: bug, enhancement

#18 hotfix and minor patches with additional features
  Core/Exception/HttpErrorResponse.cs
  Core/Exception/HttpValidResponse.cs
  Core/HttpModels/HttpResponseModel.cs
  Core/HttpModels/ObjectModels/AuthenticationToken.cs
  Core/HttpModels/ObjectModels/ClinicRegistrationModel.cs
  Core/HttpModels/ObjectModels/PasswordResetModel.cs
  Core/HttpModels/ObjectModels/UserAuthenticationRequestModel.cs
  Core/HttpModels/ObjectModels/UserInfoModel.cs
  Core/HttpModels/ObjectModels/UserRegistrationModel.cs
  Core/HttpModels/ObjectModels/VNPayInfoModel.cs
  Core/HttpModels/UserAuthenticationRequestModel.cs
  Core/HttpModels/UserInfoModel.cs
  Middlewares/JwtMiddleware.cs
  Repositories/Models/Result.cs
  Repositories/Models/Status.cs
  Repositories/Models/User.cs
  Repositories/Repositories/BookingRepository.cs
  Repositories/Repositories/ClinicRepository.cs
  Repositories/Repositories/ClinicServiceRepository.cs
  Repositories/Repositories/ClinicStaffRepository.cs
  Repositories/Repositories/Contracts/IBookingRepository.cs
  Repositories/Repositories/Contracts/IClinicRepository.cs
  Repositories/Repositories/Contracts/IClinicServiceRepository.cs
  Repositories/Repositories/Contracts/IClinicStaffRepository.cs
  Repositories/Repositories/Contracts/IGenericRepository.cs
  Repositories/Repositories/Contracts/IRoleRepository.cs
  Repositories/Repositories/Contracts/IServiceRepository.cs
  Repositories/Repositories/Contracts/IUserRepository.cs
  Repositories/Repositories/GenericRepository.cs
  Repositories/Repositories/IGenericRepository.cs
  Repositories/Repositories/RoleRepository.cs
  Repositories/Repositories/ServiceRepository.cs
  Repositories/Repositories/UserRepository.cs
  Repositories/UnitOfWork.cs
  Services/TokenManager/IJwtTokenService.cs
  Services/TokenManager/JwtTokenService.cs
  WebAPI/Controllers/AuthenticationController.cs
  WebAPI/Controllers/ClinicsController.cs
  WebAPI/Controllers/PaymentController.cs
  WebAPI/Controllers/ServiceController.cs
  WebAPI/Controllers/UsersController.cs
  WebAPI/Helper/AuthorizationPolicy/JwtTokenAuthorization.cs
Labels: documentation, enhancement

#19 Roll out main feature daily
  Core/HttpModels/HttpResponseModel.cs
  Core/HttpModels/IHttpResponseModel.cs
  Core/HttpModels/ObjectModels/AuthenticationModels/AuthenticationToken.cs
  Core/HttpModels/ObjectModels/AuthenticationModels/UserAuthenticationRequestModel.cs
  Core/HttpModels/ObjectModels/BookingModels/BookingModel.cs
  Core/HttpModels/ObjectModels/BookingModels/BookingRegistrationModel.cs
  Core/HttpModels/ObjectModels/ClinicModels/ClinicInformationModel.cs
  Core/HttpModels/ObjectModels/ClinicModels/ClinicScheduleSlotsModel.cs
  Core/HttpModels/ObjectModels/ClinicModels/ClinicServiceModel.cs
  Core/HttpModels/ObjectModels/ClinicRegistrationModel.cs
  Core/HttpModels/ObjectModels/Others/PasswordResetModel.cs
  Core/HttpModels/ObjectModels/RegistrationModels/ClinicRegistrationModel.cs
  Core/HttpModels/ObjectModels/RegistrationModels/UserRegistrationModel.cs
  Core/HttpModels/ObjectModels/RoleModels/RoleModel.cs
  Core/HttpModels/ObjectModels/UserModels/ClinicStaffInfoModel.cs
  Core/HttpModels/ObjectModels/UserModels/CustomerInfoModel.cs
  Core/HttpModels/ObjectModels/UserModels/UserInfoModel.cs
  Middlewares/AuthMiddleware/JwtMiddleware.cs
  Middlewares/LoggingMiddleware/LoggingMiddleware.cs
  Repositories/Models/Booking.cs
  Repositories/Models/ClinicService.cs
  Repositories/Models/User.cs
  Repositories/Repositories/BookingRepository.cs
  Repositories/Repositories/Contracts/IBookingRepository.cs
  Repositories/Repositories/Contracts/ICustomerRepository.cs
  Repositories/Repositories/CustomerRepository.cs
  Repositories/UnitOfWork.cs
  Services/BookingService/BookingService.cs
  Services/BookingService/IBookingService.cs
  Services/ClinicsService/ClinicsService.cs
  Services/ClinicsService/IClinicsService.cs
  Services/CustomLoggingHandler/CustomLoggingHandler.cs
  Services/CustomLoggingHandler/ICustomLoggingHandler.cs
  Services/ExceptionHandler/CustomExceptionHandler.cs
  Services/ExceptionHandler/ICustomExceptionHandler.cs
  Services/Services.csproj
  Services/TokenManager/IJwtTokenService.cs
  Services/TokenManager/JwtTokenService.cs
  Services/UserService/IUserService.cs
  Services/UserService/UserService.cs
  WebAPI/Controllers/AuthenticationController.cs
  WebAPI/Controllers/BookingController.cs
  WebAPI/Controllers/ClinicsController.cs
  WebAPI/Controllers/UsersController.cs
  WebAPI/Helper/AuthorizationPolicy/JwtTokenAuthorization.cs
  WebAPI/Helper/Mappers/MapperProfile.cs
  WebAPI/Program.cs
  WebAPI/WebAPI.csproj
  backend.sln
Labels: enhancement

#20 Update DentalClinicPlatformContext.cs
  Repositories/Models/DentalClinicPlatformContext.cs
Labels: patch

#21 Update database
  Core/HttpModels/ObjectModels/BookingModels/BookingModel.cs
  Core/HttpModels/ObjectModels/BookingModels/BookingRegistrationModel.cs
  Repositories/Models/Booking.cs
  Repositories/Models/ClinicService.cs
  Repositories/Models/DentalClinicPlatformContext.cs
  Repositories/Models/ScheduledSlot.cs
  Repositories/Models/Slot.cs
  Repositories/Models/User.cs
  Repositories/Repositories/UserRepository.cs
  Services/BookingService/BookingService.cs
  Services/ClinicsService/ClinicsService.cs
  Services/ClinicsService/IClinicsService.cs
  Services/UserService/UserService.cs
  WebAPI/Controllers/BookingController.cs
  WebAPI/Controllers/UsersController.cs
  WebAPI/Helper/Mappers/MapperProfile.cs
  backend.sln
  database/DatabaseDefinition.sql
Labels: patch

#23 Added Clinic related API endpoints for the new project
  NLayerArchitecture/ClinicPlatformBusinessObject/Models/DentalClinicPlatformContext.cs
  NLayerArchitecture/ClinicPlatformDAOs/BookingDAO.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/ClinicInfoModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/ClinicRegistrationModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/ClinicScheduleSlotsModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/ClinicScheduledSlotInfoModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/ClinicServiceInfoModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/ClinicServiceModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/ClinicSlotInfoModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/Registration/ClinicRegistrationModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/Registration/ClinicSlotRegistrationModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/Comparator/ClinicServiceComparer.cs
  NLayerArchitecture/ClinicPlatformDTOs/UserModels/ClinicStaffInfoModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/UserModels/CustomerInfoModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/UserModels/PasswordResetModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/UserModels/PasswordResetRequestModel.cs
  NLayerArchitecture/ClinicPlatformRepositories/ClinicPlatformRepositories.csproj
  NLayerArchitecture/ClinicPlatformRepositories/ClinicRepository.cs
  NLayerArchitecture/ClinicPlatformRepositories/ClinicServiceRepository.cs
  NLayerArchitecture/ClinicPlatformRepositories/Contracts/IClinicRepository.cs
  NLayerArchitecture/ClinicPlatformRepositories/Contracts/IClinicServiceRepository.cs
  NLayerArchitecture/ClinicPlatformRepositories/UserRepository.cs
  NLayerArchitecture/ClinicPlatformServices/Contracts/IClinicService.cs
  NLayerArchitecture/ClinicPlatformServices/Contracts/IUserService.cs
  NLayerArchitecture/ClinicPlatformServices/PlatformClinicService.cs
  NLayerArchitecture/ClinicPlatformServices/UserService.cs
  NLayerArchitecture/ClinicPlatformWebAPI/ClinicPlatformWebAPI.csproj
  NLayerArchitecture/ClinicPlatformWebAPI/ClinicPlatformWebAPI.http
  NLayerArchitecture/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  NLayerArchitecture/ClinicPlatformWebAPI/Controllers/PaymentController.cs
  NLayerArchitecture/ClinicPlatformWebAPI/Controllers/UserController.cs
  NLayerArchitecture/ClinicPlatformWebAPI/Program.cs
  NLayerArchitecture/ClinicPlatformWebAPI/Properties/launchSettings.json
  NLayerArchitecture/ClinicPlatformWebAPI/Services/VNPayService/IVNPayService.cs
  NLayerArchitecture/ClinicPlatformWebAPI/Services/VNPayService/VNPayService.cs
  backend.sln
Labels: enhancement, patch

#30 Added schedule
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/ClinicRegistrationModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/ClinicScheduledSlotInfoModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/ClinicModels/ClinicSlotInfoModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/SlotModels/ClinicSlotInfoModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/SlotModels/ClinicSlotRegistrationModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/SlotModels/SlotInfoModel.cs
  NLayerArchitecture/ClinicPlatformRepositories/Contracts/IScheduleRepository.cs
  NLayerArchitecture/ClinicPlatformRepositories/ScheduleRepository.cs
  NLayerArchitecture/ClinicPlatformServices/Contracts/IClinicService.cs
  NLayerArchitecture/ClinicPlatformServices/Contracts/IScheduleService.cs
  NLayerArchitecture/ClinicPlatformServices/PlatformClinicService.cs
  NLayerArchitecture/ClinicPlatformServices/ScheduleService.cs
  NLayerArchitecture/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  NLayerArchitecture/ClinicPlatformWebAPI/Program.cs
Labels: enhancement

#32 Added miminal API Endpoint for booking
  NLayerArchitecture/ClinicPlatformDAOs/BookingDAO.cs
  NLayerArchitecture/ClinicPlatformDAOs/ScheduledSlotDAO.cs
  NLayerArchitecture/ClinicPlatformDAOs/SlotDAO.cs
  NLayerArchitecture/ClinicPlatformDTOs/BookingModels/BookingModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/BookingModels/BookingRegistrationModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/BookingModels/BookingViewModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/BookingModels/SomeRandomIdea.cs
  NLayerArchitecture/ClinicPlatformDTOs/SlotModels/ClinicSlotInfoModel.cs
  NLayerArchitecture/ClinicPlatformDTOs/UserModels/PasswordResetRequestModel.cs
  NLayerArchitecture/ClinicPlatformRepositories/BookingRepository.cs
  NLayerArchitecture/ClinicPlatformRepositories/ClinicRepository.cs
  NLayerArchitecture/ClinicPlatformRepositories/Contracts/IBookingRepository.cs
  NLayerArchitecture/ClinicPlatformRepositories/ScheduleRepository.cs
  NLayerArchitecture/ClinicPlatformServices/BookingService.cs
  NLayerArchitecture/ClinicPlatformServices/Contracts/IBookingService.cs
  NLayerArchitecture/ClinicPlatformServices/PlatformClinicService.cs
  NLayerArchitecture/ClinicPlatformServices/ScheduleService.cs
  NLayerArchitecture/ClinicPlatformWebAPI/ClinicPlatformWebAPI.csproj
  NLayerArchitecture/ClinicPlatformWebAPI/Controllers/BookingController.cs
  NLayerArchitecture/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  NLayerArchitecture/ClinicPlatformWebAPI/Controllers/UserController.cs
  NLayerArchitecture/ClinicPlatformWebAPI/Program.cs
Labels: enhancement, experimental

#37 Updated Clinic Repository
  DentalClinicBookingPlatform/ClinicPlatformDTOs/ClinicModels/ClinicInfoUpdateModel.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/ClinicRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/UserRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PlatformClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ScheduleController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Helpers/ModelMapper/ClinicMapper.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Middlewares/Auth/AuthorizationMiddleware.cs
Labels: patch

#39 Fixed authorization middleware related bug
  DentalClinicBookingPlatform/ClinicPlatformDTOs/ServiceModels/ClinicServiceRegistrationModel.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/BookingRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/ClinicServiceRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/Contracts/IClinicServiceRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PlatformClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AdminController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/CustomerController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ScheduleController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Helpers/ModelMapper/ClinicMapper.cs
Labels: patch

#41 Another updates
  DentalClinicBookingPlatform/ClinicPlatformDTOs/ServiceModels/ClinicServiceCategoryModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/ServiceModels/ClinicServiceCategoryRegistrationModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/SlotModels/ClinicSlotUpdateModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/CustomerModel/CustomerInfoViewModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/CustomerModel/CustomerRegistrationModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/CustomerModel/CustomerUpdateModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/DentistModel/DentistInfoViewModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/DentistModel/DentistRegistrationModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/DentistModel/DentistUpdateModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/UserModels/UserInfoModel.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/ClinicServiceRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/Contracts/IClinicServiceRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/ScheduleRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/UserRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/ClinicServiceService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IClinicServiceService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IUserService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PlatformClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/ScheduleService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/UserService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AdminController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/CustomerController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/DentistController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ScheduleController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/UserController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Helpers/ModelMapper/ClinicMapper.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Helpers/ModelMapper/UserInfoMapper.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Middlewares/Auth/AuthorizationMiddleware.cs
  TestProject/UserRepositoryTesting.cs
Labels: enhancement, patch

#42 Update for clinic service and slot.
  DentalClinicBookingPlatform/ClinicPlatformRepositories/ClinicServiceRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/PlatformClinicService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/ScheduleService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/UserService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicServiceController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/DentistController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ScheduleController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Helpers/Models/HttpResponseModel.cs
Labels: enhancement, patch

#43 Fixed authentication
  DentalClinicBookingPlatform/ClinicPlatformServices/UserService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/DentistController.cs
Labels: patch

#44 Fixed single appointment creation functionality.
  DentalClinicBookingPlatform/ClinicPlatformDTOs/BookingModels/AppointmentInfoModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/BookingModels/AppointmentRegistrationModel.cs
  DentalClinicBookingPlatform/ClinicPlatformDTOs/BookingModels/BookedServiceInfoModel.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/ClinicServiceRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/UserRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/BookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IBookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IScheduleService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/Contracts/IUserService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/ScheduleService.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/UserService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/BookingController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/DentistController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ScheduleController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Helpers/ModelMapper/AppointmentMapper.cs
Labels: enhancement, patch

#45 Fixed Dentist endpoint
  DentalClinicBookingPlatform/ClinicPlatformRepositories/ClinicServiceRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/AuthService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/AuthController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/ClinicServiceController.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/DentistController.cs
Labels: enhancement, patch

#46 Fixed error while fetching booking data
  DentalClinicBookingPlatform/ClinicPlatformDTOs/BookingModels/AppointmentRegistrationModel.cs
  DentalClinicBookingPlatform/ClinicPlatformRepositories/UserRepository.cs
  DentalClinicBookingPlatform/ClinicPlatformServices/BookingService.cs
  DentalClinicBookingPlatform/ClinicPlatformWebAPI/Controllers/BookingController.cs
Labels: patch
